name: compile release

on:
  push:
    branches: [ main, devel ]
  schedule:
    - cron: "32 14 3,17 * *"

jobs:
  
  build:
    runs-on: ubuntu-latest
    strategy:
      
      fail-fast: false
      matrix:
        target: # find -L build/ -type f ! -name '*.keys' -printf '%f\n' | sort
          - busybox
          - curl
          - fdisk
          - git
          - gpg
          - make
          - openssl
          - rsync
          - squashfs
          - vim
          - zstd
    
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile static binaries for target
        run: |
          make clean
          make ${{ matrix.target }} || \
            (echo "=== RETRY 1 ==="; make ${{ matrix.target }} ) || \
            (echo "=== RETRY 2 ==="; make ${{ matrix.target }} )
          make sources/${{ matrix.target }}.tar

      - name: Upload job artifact
        uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/main'
        with:
          name: ${{ matrix.target }}
          path: |
            compiled/native/${{ matrix.target }}/
            sources/${{ matrix.target }}.tar
          retention-days: 60
