name: compile release

on:
  push:
    branches: [ main,  devel ]
  schedule:
    - cron: "32 14 3,17 * *"

jobs:
  
  build:
    runs-on: ubuntu-latest
    strategy:
      
      fail-fast: false
      matrix:
        bin:
          - busybox
          - curl
          - fdisk
          - git
          - gpg
          - make
          - rsync
          - vim
          - zstd
    
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile static binary
        run: |
          rm -rf compiled/
          make ${{ matrix.bin }} || \
            (echo "=== RETRY 1 ==="; make ${{ matrix.bin }} ) || \
            (echo "=== RETRY 2 ==="; make ${{ matrix.bin }} )
          make ${{ matrix.bin }}-sources

      - name: Upload job artifact
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/main'
        with:
          name: ${{ matrix.bin }}
          path: compiled/*
          retention-days: 60
