name: cross-compile all targets for all platforms

# only manual trigger
on: workflow_dispatch

jobs:
  
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: # find -L build/ -type f ! -name '*.keys' -printf '"%f"\n' | sort | jq -s | yq -y
          - busybox
          - curl
          - fdisk
          - git
          - gpg
          - make
          - openssl
          - rsync
          - squashfs
          - vim
          - zstd
        platform: # sed -n 's/^* `\([a-z0-9-]\+\)`$/- \1/p' README.md
          - linux-amd64
          - linux-arm64
          - linux-armv7
          - linux-armv6
          - linux-riscv64
          - linux-s390x
          - linux-386

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Compile static binaries for target
        run: |
          make clean
          make compiled/${{ matrix.platform }}/${{ matrix.target }}/
          make sources/${{ matrix.target }}.tar

      - name: Upload job artifact
        uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/main'
        with:
          name: ${{ matrix.target }}-${{ matrix.platform }}
          path: |
            compiled/*
            sources/*
          retention-days: 60
