name: cross-compile all targets for all platforms

# only manual trigger
on: workflow_dispatch

jobs:

  # create a build matrix with the available make targets
  list-targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.listing.outputs.targets }}
      platforms: ${{ steps.listing.outputs.platforms }}
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: list available make targets and buildx platforms
        id: listing
        run: |
          make list-targets \
          | jq -Rsc 'split(" ")[:-1]' \
          | sed 's:^:targets=:' >> $GITHUB_OUTPUT
          make list-platforms \
          | jq -Rsc 'split(" ")[:-1]' \
          | sed 's:^:platforms=:' >> $GITHUB_OUTPUT

  # compile binaries for available targets listed above
  build:
    runs-on: ubuntu-latest
    needs: list-targets
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.list-targets.outputs.targets) }}
        platform: ${{ fromJson(needs.list-targets.outputs.platforms) }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Compile static binaries for target
        run: |
          make clean
          make compiled/${{ matrix.platform }}/${{ matrix.target }}/
          make sources/${{ matrix.target }}.tar

      - name: Upload job artifact
        uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/main'
        with:
          name: ${{ matrix.target }}-${{ matrix.platform }}
          path: |
            compiled/*
            sources/*
          retention-days: 60
